config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  mount Ckeditor::Engine => '/ckeditor'

  get 'parts/kombikorm', to: redirect('roottypes/1')
  get 'parts/pellet', to: redirect('roottypes/2')

  get 'types/update_parts', as: 'update_parts'
  get 'types/:id/update_parts' => 'types#update_parts'

  get 'items/update_types', as: 'update_types'
  get 'items/update_parts' => 'types#update_parts'
  get 'items/:id/update_types' => 'items#update_types'
  get 'items/:id/update_parts' => 'types#update_parts'

  get 'roottypes_order' => 'roottypes#order', as: 'roottypes_order'
  get 'parts_order' => 'parts#order', as: 'parts_order'
  get 'types_order' => 'types#order', as: 'types_order'
  get 'items_order' => 'items#order', as: 'items_order'

  get 'roottypes/:id/up_order' => 'roottypes#up_order', as: 'roottypes_up_order'
  get 'roottypes/:id/down_order' => 'roottypes#down_order', as: 'roottypes_down_order'

  get 'parts/:id/up_order' => 'parts#up_order', as: 'parts_up_order'
  get 'parts/:id/down_order' => 'parts#down_order', as: 'parts_down_order'

  get 'types/:id/up_order' => 'types#up_order', as: 'types_up_order'
  get 'types/:id/down_order' => 'types#down_order', as: 'types_down_order'

  get 'items/:id/up_order' => 'items#up_order', as: 'items_up_order'
  get 'items/:id/down_order' => 'items#down_order', as: 'items_down_order'

  post 'callbacks/fast_callback'
  post 'callbacks/slow_callback'
  patch 'callbacks/slow_callback'
  patch 'callbacks/fast_callback'

  resources :admins
  resources :actions
  resources :tidings
  resources :parts
  resources :types
  resources :items
  resources :comments
  resources :captions
  resources :sliders
  resources :uploads
  resources :abouts, :only => [:index, :edit, :update]
  resources :mains, :only => [:index, :edit, :update]
  resources :contacts, :only => [:index]
  resources :globals
  resources :photogals
  resources :photogal_assets, :only => [:edit, :update]
  resources :roottypes
  root 'static#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/publish_item/:id', to: 'items#publish', as: 'publish_item'
  get '/dublicate/:id', to: 'items#dublicate', as: 'dublicate'

  get '/destroy_item_asset/:item_id/:asset_id', to: 'items#destroy_asset', as: 'destroy_item_asset'
  get '/destroy_photogal_asset/:photogal_id/:asset_id', to: 'photogals#destroy_asset', as: 'destroy_photogal_asset'
end

app/models/about.rb
class About < ActiveRecord::Base
  has_many :about_assets, :as => :attachable
  accepts_nested_attributes_for :about_assets, :allow_destroy => true
end

app/models/about_asset.rb
class AboutAsset < ActiveRecord::Base
  belongs_to :attachable, :polymorphic => true
  has_attached_file :asset, :styles => { :mikro => "100x100#", :mini => "290x180>", :normal => "380x300>" }
  do_not_validate_attachment_file_type :asset
  # validates_attachment_content_type :file_name, :content_type => %w(image/jpeg image/jpg image/png)
end

app/models/action.rb
class Action < ActiveRecord::Base
  is_impressionable

  has_attached_file :image, :styles => {:preview => "310x230#"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :title, :presence=>true
  validates :body, :presence=>true
  validates :created_at, date: true
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessor :remember_token # virtual param (not in DB)
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
      format: { with: VALID_EMAIL_REGEX },
      uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  # Returns the hash digest of the given string (for admin_login test)
  def Admin.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Admin.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers an admin in the database for use in persistent sessions.
  def remember
    self.remember_token = Admin.new_token
    update_attribute(:remember_digest, Admin.digest(remember_token))
  end

  # Forgets an admin.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

app/models/caption.rb
class Caption < ActiveRecord::Base
  validates :body, presence: true, length: { maximum: 50 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :presence=>true
  validates :body, :presence=>true
  validates :email, presence: true, length: { maximum: 255 },
      format: { with: VALID_EMAIL_REGEX },
      uniqueness: { case_sensitive: false }
  validates :created_at, date: true, :on => :update
end

app/models/global.rb
class Global < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :address, :workStart, :workEnd, :phone, presence: true
  validates :email, presence: true, length: { maximum: 255 },
      format: { with: VALID_EMAIL_REGEX }
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :type

  has_many :attached_assets, :as => :attachable
  accepts_nested_attributes_for :attached_assets, :allow_destroy => true

  validates :body, :presence => true
  validates :title, :presence => true
  default_scope { order(:order) }
end

app/models/main.rb
class Main < ActiveRecord::Base
end

app/models/part.rb
class Part < ActiveRecord::Base
  has_many :types
  belongs_to :roottype
  accepts_nested_attributes_for :types, :allow_destroy => true
  validates_presence_of :title
  default_scope { order(:order) }
end

app/models/photogal.rb
class Photogal < ActiveRecord::Base
  has_many :photogal_assets, :as => :attachable
  accepts_nested_attributes_for :photogal_assets, :allow_destroy => true
end

app/models/roottype.rb
class Roottype < ActiveRecord::Base
  has_many :parts
  accepts_nested_attributes_for :parts, :allow_destroy => true
  validates :title, :presence => true
  default_scope { order(:order) }
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_attached_file :image, :styles => { :normal => "1123x300>", :preview => "200x100>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/tiding.rb
class Tiding < ActiveRecord::Base
  is_impressionable

  has_attached_file :image, :styles => {:preview => "310x230#"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :title, :presence=>true
  validates :body, :presence=>true
  validates :created_at, date: true
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :items
  belongs_to :part
  accepts_nested_attributes_for :items, :allow_destroy => true
  validates :title, :presence => true
  default_scope { order(:order) }
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :asset
  do_not_validate_attachment_file_type :asset

  validates :name, presence: true, length: { maximum: 50 }
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/admins/_toolbar.html.erb
<% if logged_in? %>
    <p>
      <%= link_to 'Добавить категорию', new_roottype_path, :class => "btn btn-primary btn-add" %>
      <%= link_to 'Добавить раздел', new_part_path, :class => "btn btn-primary btn-add" %>
      <%= link_to 'Добавить подраздел', new_type_path, :class => "btn btn-primary btn-add" %>
      <%= link_to 'Добавить материал', new_item_path, :class => "btn btn-primary btn-item" %>
      <%= link_to 'Управление сортировкой', roottypes_order_path, :class => "btn btn-primary" %>
    </p>
<% end %>

app/views/admins/edit.html.erb
<% breadcrumb :edit_admin %>
<%= render 'shared/admins_error_messages' %>
<div class="login">
  <%= form_for(@admin) do |f| %>
      <%= f.label :name, 'Имя' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password, 'Пароль' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Подтверждение пароля" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Сохранить", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admins/new.html.erb
<% breadcrumb :new_admin %>
<%= render 'shared/admins_error_messages' %>
<div class="login">
  <%= form_for(@admin) do |f| %>
      <%= f.label :name, 'Имя' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password, 'Пароль' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Подтверждение пароля" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Зарегистрировать", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admins/update.html.erb
<h1>Admins#update</h1>
<p>Find me in app/views/admins/update.html.erb</p>

app/views/shared/_abouts_error_messages.html.erb
<% if @body.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@body.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @body.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_actions_error_messages.html.erb
<% if @action.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@action.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @action.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_admins_error_messages.html.erb
<% if @admin.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@admin.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @admin.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_captions_error_messages.html.erb
<% if @caption.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@caption.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @caption.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_comments_error_messages.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@comment.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_contacts_error_messages.html.erb
<% if @body.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@body.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @body.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_globals_error_messages.html.erb
<% if @global.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@global.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @global.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_items_error_messages.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@item.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_parts_error_messages.html.erb
<% if @part.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@part.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @part.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_photogal_assets_error_message.html.erb
<% if @asset.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        Форма содержит <%= Russian::pluralize(@asset.errors.count, "ошибку", "ошибки", "ошибок") %>.
      </div>
      <ul>
        <% @asset.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_roottypes_error_messages.html.erb
<% if @roottype.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        Форма содержит <%= Russian::pluralize(@roottype.errors.count, "ошибку", "ошибки", "ошибок") %>.
      </div>
      <ul>
        <% @roottype.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_tidings_error_messages.html.erb
<% if @tiding.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@tiding.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @tiding.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_types_error_messages.html.erb
<% if @type.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Форма содержит <%= Russian::pluralize(@type.errors.count, "ошибку", "ошибки", "ошибок") %>.
    </div>
    <ul>
    <% @type.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>