config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  mount Ckeditor::Engine => '/ckeditor'

  get 'parts/kombikorm', to: redirect('roottypes/1')
  get 'parts/pellet', to: redirect('roottypes/2')

  get 'types/update_parts', as: 'update_parts'
  get 'types/:id/update_parts' => 'types#update_parts'

  get 'items/update_types', as: 'update_types'
  get 'items/update_parts' => 'types#update_parts'
  get 'items/:id/update_types' => 'items#update_types'
  get 'items/:id/update_parts' => 'types#update_parts'

  get 'roottypes_order' => 'roottypes#order', as: 'roottypes_order'
  get 'parts_order' => 'parts#order', as: 'parts_order'
  get 'types_order' => 'types#order', as: 'types_order'
  get 'items_order' => 'items#order', as: 'items_order'

  get 'roottypes/:id/up_order' => 'roottypes#up_order', as: 'roottypes_up_order'
  get 'roottypes/:id/down_order' => 'roottypes#down_order', as: 'roottypes_down_order'

  get 'parts/:id/up_order' => 'parts#up_order', as: 'parts_up_order'
  get 'parts/:id/down_order' => 'parts#down_order', as: 'parts_down_order'

  get 'types/:id/up_order' => 'types#up_order', as: 'types_up_order'
  get 'types/:id/down_order' => 'types#down_order', as: 'types_down_order'

  get 'items/:id/up_order' => 'items#up_order', as: 'items_up_order'
  get 'items/:id/down_order' => 'items#down_order', as: 'items_down_order'

  post 'callbacks/fast_callback'
  post 'callbacks/slow_callback'
  patch 'callbacks/slow_callback'
  patch 'callbacks/fast_callback'

  resources :admins
  resources :actions
  resources :tidings
  resources :parts
  resources :types
  resources :items
  resources :comments
  resources :captions
  resources :sliders
  resources :uploads
  resources :abouts, :only => [:index, :edit, :update]
  resources :mains, :only => [:index, :edit, :update]
  resources :contacts, :only => [:index]
  resources :globals
  resources :photogals
  resources :photogal_assets, :only => [:edit, :update]
  resources :roottypes
  root 'static#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/publish_item/:id', to: 'items#publish', as: 'publish_item'
  get '/dublicate/:id', to: 'items#dublicate', as: 'dublicate'

  get '/destroy_item_asset/:item_id/:asset_id', to: 'items#destroy_asset', as: 'destroy_item_asset'
  get '/destroy_photogal_asset/:photogal_id/:asset_id', to: 'photogals#destroy_asset', as: 'destroy_photogal_asset'
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
# encoding: UTF-8
  before_action :logged_in_admin, only: [:edit, :update, :new, :up_order, :down_order, :order]

  def order
    @part = Part.find(params[:part_id])
    @types = Type.where(part_id: params[:part_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @type = Type.find(params[:id])
    @type.destroy
    flash[:success] = "Подраздел удален"
    redirect_to parts_url
  end

  def update_parts
    @parts = Roottype.find(params[:roottype]).parts
    @types = @parts.first.types
    respond_to do |format|
      format.js
    end
  end

  def edit
    @type = Type.find(params[:id])
    @part = @type.part
    @parts = @part.roottype.parts
    @items = Item.where("type_id = ? AND public = ?", @type.id, true)
  end

  def update
    @type = Type.find(params[:id])
    if @type.update_attributes(types_params)
      # Handle a successful update.
      flash[:success] = "Раздел обновлен"
      redirect_to type_url(@type.id)
    else
      render 'edit'
    end
  end

  def show
    @type = Type.find(params[:id])
    @thumb_item = Item.find(@type.thumb_item_id) if @type.thumb_item_id
    @counter = @type.items.where("public = ?", true).count

    if logged_in? == false
      if @counter > 0
        @items = @type.items.where("public = ?", true)
      else
        logged_in_admin
      end
    else
      @items = @type.items.all
    end
  end

  def new
    @type = Type.new
  end

  def create
    @type = Type.new(types_params)
    types = Type.where(part_id: @type.part_id)
    last_order = types.empty? ? 1 : types.last.order + 1
    @type.order = last_order
    if @type.save
      # Handle a successful save.
      flash[:success] = "Подраздел добавлен"
      redirect_to type_url(@type.id)
    else
      render 'new'
    end
  end

  def up_order
    type = Type.find(params[:id])

    upper_type = Type.where(order: type.order-1, part_id: type.part_id).first
    upper_type.update_attributes(order: upper_type.order+1)
    type.update_attributes(order: type.order-1)

    redirect_to types_order_path(:part_id => type.part_id)
  end

  def down_order
    type = Type.find(params[:id])

    downer_type = Type.where(order: type.order+1, part_id: type.part_id).first
    downer_type.update_attributes(order: downer_type.order-1)
    type.update_attributes(order: type.order+1)

    redirect_to types_order_path(:part_id => type.part_id)
  end
end

def index
end

def up_order
  type = Type.find(params[:id])

  upper_type = Type.where(order: type.order-1, part_id: type.part_id).first
  upper_type.update_attributes(order: upper_type.order+1)
  type.update_attributes(order: type.order-1)

  redirect_to types_order_path, :id => type.part_id
end

def down_order
  type = Type.find(params[:id])

  upper_type = Type.where(order: type.order+1, part_id: type.part_id).first
  upper_type.update_attributes(order: upper_type.order-1)
  type.update_attributes(order: type.order+1)

  redirect_to types_order_path, :id => type.part_id
end


private
def types_params
  params.require(:type).permit(:title, :part_id, :thumb_item_id)
end

# Confirms a logged-in user.
def logged_in_admin
  unless logged_in?
    store_location
    flash[:danger] = "Зайдите как администратор"
    redirect_to login_url
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_card.html.erb
<% if logged_in? %>
    <div class="col-md-2 col-sm-2 col-xs-2 col-fixed col-centered">
      <% @thumb = type.thumb_item_id != nil ? Item.find(type.thumb_item_id) : type.items.first %>
      <% image = image_tag(@thumb.attached_assets.first.asset.url(:mini)) if @thumb && !@thumb.attached_assets.empty? && @thumb.attached_assets.first.asset %>

      <%= link_to image, type_path(type.id) if image %>
      <%= link_to "#{type.title} <br> (<span class='publish'>#{type.items.where("public = ?", true).count}</span>/#{type.items.all.count})".html_safe, type_path(type.id) %>
      <%= link_to "", edit_type_path(type), :class => "btn-edit" %>
      <%= link_to "", type, :class => "btn-delete", method: :delete, data: {confirm: "Вы уверены?"} %>
    </div>
<% elsif !logged_in? && type.items.where("public = ?", true).count > 0 %>
    <div class="col-md-2 col-sm-2 col-xs-2 col-fixed col-centered">
      <% @thumb = type.thumb_item_id != nil ? Item.find(type.thumb_item_id) : type.items.first %>
      <% image = image_tag(@thumb.attached_assets.first.asset.url(:mini)) if @thumb && !@thumb.attached_assets.empty? && @thumb.attached_assets.first.asset %>

      <% if type.items.where("public = ?", true).count == 1 %>
          <%= link_to image, item_path(type.items.where("public = ?", true).first.id) if image %>
          <%= link_to type.items.where("public = ?", true).first.title, item_path(type.items.where("public = ?", true).first.id) %>
      <% else %>
          <%= link_to image, type_path(type.id) if image %>
          <%= link_to type.title, type_path(type.id) %>
      <% end %>
    </div>
<% end %>

app/views/types/_card.html_backup.erb
<% if logged_in? %>
    <div class="col-md-2 col-sm-2 col-xs-2 col-fixed col-centered">
      <% @thumb = type.thumb_item_id != nil ? Item.find(type.thumb_item_id) : type.items.first %>
      <% image = image_tag(@thumb.attached_assets.first.asset.url(:mini)) if @thumb && !@thumb.attached_assets.empty? && @thumb.attached_assets.first.asset %>

      <%= link_to image, type_path(type.id) if image %>
      <%= link_to "#{type.title} <br> (<span class='publish'>#{type.items.where("public = ?", true).count}</span>/#{type.items.all.count})".html_safe, type_path(type.id) %>
      <%= link_to "", edit_type_path(type), :class => "btn-edit" %>
      <%= link_to "", type, :class => "btn-delete", method: :delete, data: {confirm: "Вы уверены?"} %>
    </div>
<% elsif !logged_in? && type.items.where("public = ?", true).count > 0 %>
    <div class="col-md-2 col-sm-2 col-xs-2 col-fixed col-centered">
      <% @thumb = type.thumb_item_id != nil ? Item.find(type.thumb_item_id) : type.items.first %>
      <% image = image_tag(@thumb.attached_assets.first.asset.url(:mini)) if @thumb && !@thumb.attached_assets.empty? && @thumb.attached_assets.first.asset %>

      <% if type.items.where("public = ?", true).count == 1 %>
          <%= link_to image, item_path(type.items.where("public = ?", true).first.id) if image %>
          <%= link_to type.items.where("public = ?", true).first.title, item_path(type.items.where("public = ?", true).first.id) %>
      <% else %>
          <%= link_to image, type_path(type.id) if image %>
          <%= link_to type.title, type_path(type.id) %>
      <% end %>
    </div>
<% end %>

app/views/types/_type.html.erb
<option value="<%= type.id %>"><%= type.title %></option>

app/views/types/edit.html.erb
<% breadcrumb :edit_type, @type %>
<%= render 'shared/types_error_messages' %>
<div class="col-md-4">
  <%= form_for(@type) do |f| %>

      <%= f.label 'Тип оборудования' %>
      <%= f.collection_select :roottype, Roottype.all, :id, :title,
                              {:selected => @type.part.roottype_id}, {:class => 'form-control', :id=>'roottypes_select' } %>

      <%= f.label :part_id, 'Раздел' %>
      <%= f.collection_select :part_id, @parts, :id, :title, {:selected => @type.part_id}, {:class => 'form-control', :id => 'parts_select' } %>

      <%= f.label :title, 'Наименование' %>

      <%= f.text_field :title, class: 'form-control' %>

          <%= f.label :thumb_item_id, 'Превью' %>
          <%= f.collection_select :thumb_item_id, @items, :id, :title, {}, {:class => 'form-control'} %>
      <%= f.submit "Сохранить", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/types/new.html.erb
<% breadcrumb :add_type %>
<%= render 'shared/types_error_messages' %>
<div class="col-md-4">
  <%= form_tag do %>
      <%= label_tag 'Тип оборудования' %>
      <%= collection_select :roottype, :title, Roottype.all || [], :id, :title,
                            {:selected => @type.part.nil? ? "" : @type.part.roottype_id}, {:class => 'form-control', :id => 'roottypes_select'} %>
  <% end %>
  <%= form_for(@type) do |f| %>
      <%= f.label :part_id, 'Раздел' %>
      <%= f.collection_select :part_id, @parts || [], :id, :title,
                              {:selected => @type.part_id}, {:class => 'form-control', :id => 'parts_select'} %>

      <%= f.label :title, 'Наименование' %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.submit "Добавить", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/types/order.html.erb
<% breadcrumb :types_order, @part %>
<% @types.each_with_index do |type, index| %>
    <p>
      <% if index != 0 %>
          <%= link_to '', types_up_order_path(type.id), :class => "btn-up" %>
      <% end %>
      <% if index != @types.count-1 %>
          <%= link_to '', types_down_order_path(type.id), :class => "btn-down" %>
      <% end %>
      <% if type.items.count > 1 %>
          <b><%= link_to type.title, items_order_path(type_id: type.id) %></b>
      <% else %>
          <b><%= type.title %></b>
      <% end %>
    </p>
<% end %>

app/views/types/show.html.erb
<% breadcrumb :type, @type, @part, @roottype %>
<%= render 'admins/toolbar' %>
<div class="row">
  <%= render 'parts/items_tree_menu' %>
  <div class="col-md-9 catalog">
    <h2><%= @type.title %></h2>

    <div class="row row-centered">
      <div class="masonry">
        <ul>
          <% if @items.first %>
              <% @items.each do |item| %>
                  <%= render partial: "items/card", :locals => {:item => item} %>
              <% end %>
          <% else %>
              <div class="col-md-2 col-sm-2 col-xs-2 col-fixed col-centered">
                Материалов нет
              </div>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/types/types_order.html.erb
<% @types.each_with_index do |type, index| %>
    <p>
      <% if index != 0 %>
          <%= link_to '', types_up_order_path(type.id), :class => "btn-up" %>
      <% end %>
      <% if index != @types.count-1 %>
          <%= link_to '', types_down_order_path(type.id), :class => "btn-down" %>
      <% end %>
      <b><%= link_to type.title, type_path(type.id) %></b>
    </p>
<% end %>