config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  mount Ckeditor::Engine => '/ckeditor'

  get 'parts/kombikorm', to: redirect('roottypes/1')
  get 'parts/pellet', to: redirect('roottypes/2')

  get 'types/update_parts', as: 'update_parts'
  get 'types/:id/update_parts' => 'types#update_parts'

  get 'items/update_types', as: 'update_types'
  get 'items/update_parts' => 'types#update_parts'
  get 'items/:id/update_types' => 'items#update_types'
  get 'items/:id/update_parts' => 'types#update_parts'

  get 'roottypes_order' => 'roottypes#order', as: 'roottypes_order'
  get 'parts_order' => 'parts#order', as: 'parts_order'
  get 'types_order' => 'types#order', as: 'types_order'
  get 'items_order' => 'items#order', as: 'items_order'

  get 'roottypes/:id/up_order' => 'roottypes#up_order', as: 'roottypes_up_order'
  get 'roottypes/:id/down_order' => 'roottypes#down_order', as: 'roottypes_down_order'

  get 'parts/:id/up_order' => 'parts#up_order', as: 'parts_up_order'
  get 'parts/:id/down_order' => 'parts#down_order', as: 'parts_down_order'

  get 'types/:id/up_order' => 'types#up_order', as: 'types_up_order'
  get 'types/:id/down_order' => 'types#down_order', as: 'types_down_order'

  get 'items/:id/up_order' => 'items#up_order', as: 'items_up_order'
  get 'items/:id/down_order' => 'items#down_order', as: 'items_down_order'

  post 'callbacks/fast_callback'
  post 'callbacks/slow_callback'
  patch 'callbacks/slow_callback'
  patch 'callbacks/fast_callback'

  resources :admins
  resources :actions
  resources :tidings
  resources :parts
  resources :types
  resources :items
  resources :comments
  resources :captions
  resources :sliders
  resources :uploads
  resources :abouts, :only => [:index, :edit, :update]
  resources :mains, :only => [:index, :edit, :update]
  resources :contacts, :only => [:index]
  resources :globals
  resources :photogals
  resources :photogal_assets, :only => [:edit, :update]
  resources :roottypes
  root 'static#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/publish_item/:id', to: 'items#publish', as: 'publish_item'
  get '/dublicate/:id', to: 'items#dublicate', as: 'dublicate'

  get '/destroy_item_asset/:item_id/:asset_id', to: 'items#destroy_asset', as: 'destroy_item_asset'
  get '/destroy_photogal_asset/:photogal_id/:asset_id', to: 'photogals#destroy_asset', as: 'destroy_photogal_asset'
end

app/models/tiding.rb
class Tiding < ActiveRecord::Base
  is_impressionable

  has_attached_file :image, :styles => {:preview => "310x230#"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :title, :presence=>true
  validates :body, :presence=>true
  validates :created_at, date: true
end

app/controllers/tidings_controller.rb
class TidingsController < ApplicationController
  # encoding: UTF-8
  respond_to :html, :xml, :json, :js
  before_action :logged_in_admin, only: [:edit, :update, :new]
  impressionist :actions=>[:show, :index]
  def index
    get_and_show_posts
  end


  def show
    @tiding = Tiding.find(params[:id])
    @impression = @tiding.impressionist_count(:filter=>:all)
  end
  def new
    @tiding = Tiding.new
  end
  def create
    @tiding = Tiding.new(tidings_param)
    if @tiding.save
      # Handle a successful save.
      flash[:success] = "Новость добавлена"
      redirect_to tidings_url
    else
      render 'new'
    end
  end
  def edit
    @tiding = Tiding.find(params[:id])
  end
  def update
    @tiding = Tiding.find(params[:id])
    if @tiding.update_attributes(tidings_param)
      # Handle a successful update.
      flash[:success] = "Новость обновлена"
      redirect_to tidings_url
    else
      render 'edit'
    end
  end
  def destroy
    @tiding = Tiding.find(params[:id])
    @tiding.destroy
    flash[:success] = "Новость удалена"
    redirect_to tidings_url
  end
  private
  def tidings_param
    params.require(:tiding).permit(:image, :title, :body, :created_at)
  end
  # Confirms a logged-in user.
  def logged_in_admin
    unless logged_in?
      store_location
      flash[:danger] = "Зайдите как администратор"
      redirect_to login_url
    end
  end

  def get_and_show_posts
    @tidings = Tiding.paginate(page: params[:page], per_page: 3).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/tidings_helper.rb
module TidingsHelper
end

app/views/tidings/_tiding.html.erb
<% require 'nokogiri' %>
<% parser = Nokogiri::HTML(tiding.body) %>
<% parser.search('img').remove %>

<div class="blog-item col-md-4">
  <% if logged_in? %>
      <p class="admin">
        <%= link_to "Изменить", edit_tiding_path(tiding), :class => "btn btn-sm btn-primary" %>
        <%= link_to "Удалить", tiding, :class => "btn btn-sm btn-danger", method: :delete, data: { confirm: "Вы уверены?" } %>
      </p>
  <% end %>

  <div class="preview-image">
    <%= link_to (image_tag tiding.image.url(:preview)), tiding_path(tiding.id) %>
  </div>

  <h3><%= link_to tiding.title, tiding_path(tiding.id) %></h3>

  <p><%= truncate(raw(parser), length: 255, :escape => false) %></p>

  <p class="views">
    Добавлено: <%= tiding.created_at.strftime("%d.%m.%y") %><br>
    Просмотров: <%= tiding.impressionist_count(:filter => :all) %>
  </p>

  <p class="read">
    <%= link_to "Читать полностью", tiding_path(tiding.id) %>
  </p>

</div>

app/views/tidings/edit.html.erb
<% breadcrumb :edit_tiding, @tiding %>
<%= render 'shared/tidings_error_messages' %>
<%= form_for(@tiding) do |f| %>

    <%= f.label :title, 'Заголовок' %></li>
    <%= f.text_field :title, class:'form-control' %>
    <%= f.label :body, 'Текст новости' %>
    <%= f.cktext_area :body, :class => 'form-control', :ckeditor => {:language => 'ru'} %>
    <div class="file_upload">+ <%= f.file_field :image %> </div> <b>Загрузить превью</b><br>
    <br />
    <%= f.text_field :created_at, "data-parsley-trigger" => "change", "data-parsley-date" => '', 'required' => '', :placeholder => 'Дата публикации', class: "datepicker form-control" %>

    <%= f.submit "Изменить", class: "btn btn-primary" %>
<% end %>

app/views/tidings/index.html.erb
<% breadcrumb :tidings %>
<% if logged_in? %>
    <p><%= link_to 'Добавить новость', new_tiding_path, :class => "btn btn-item btn-primary" %></p>
<% end %>

<div id="my-tidings">
  <div class="page-delimiter first-page" data-page="<%= params[:page] || 1 %>"></div>
  <div class="row tidings">
    <%= render @tidings %>
  </div>
</div>

<div id="infinite-scrolling">
  <%= will_paginate @tidings %>
</div>

app/views/tidings/index.js.erb
$('#my-tidings').append('<div class="row"><%= j render @tidings %></div>');
<% if @tidings.next_page %>
$('.pagination').replaceWith('<%= j will_paginate @tidings %>');
<% else %>
$(window).off('scroll');
$('.pagination').remove();
<% end %>

app/views/tidings/new.html.erb
<% breadcrumb :add_tiding %>
<%= render 'shared/tidings_error_messages' %>
<%= form_for(@tiding) do |f| %>

    <%= f.label :title, 'Заголовок' %></li>
    <%= f.text_field :title, class:'form-control' %>
    <%= f.label :body, 'Текст новости' %>
    <%= f.cktext_area :body, :class => 'form-control', :ckeditor => {:language => 'ru'} %>
    <div class="file_upload">+ <%= f.file_field :image %> </div> <b>Загрузить превью</b><br>
    <br />
    <%= f.text_field :created_at, "data-parsley-trigger" => "change", "data-parsley-date" => '', 'required' => '', :placeholder => 'Дата публикации', class: "datepicker form-control" %>
    <%= f.submit "Добавить", class: "btn btn-primary" %>

<% end %>

app/views/tidings/show.html.erb
<% require 'nokogiri' %>
<% parser = Nokogiri::HTML(@tiding.body) %>
<% img = parser.css('img') %>
<% img.add_class('tiding-img') %>
<% parser.search('img').remove %>

<% breadcrumb :tiding, @tiding %>
<%= raw(img) %>
<p>
<h3><%= @tiding.title %></h3>
<%= raw(parser) %>
</p>
<p> Дата создания: <%= @tiding.created_at.strftime("%d.%m.%y") %>, Просмотров: <%= @impression %></p>
<% if logged_in? %>
    <p class="admin">
      <%= link_to "Изменить", edit_tiding_path(@tiding), :class => "btn btn-edit btn-sm btn-primary" %>
      <%= link_to "Удалить", @tiding, :class => "btn btn-sm btn-danger", method: :delete, data: { confirm: "Вы уверены?" } %>
    </p>
<% end %>