config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  mount Ckeditor::Engine => '/ckeditor'

  get 'parts/kombikorm', to: redirect('roottypes/1')
  get 'parts/pellet', to: redirect('roottypes/2')

  get 'types/update_parts', as: 'update_parts'
  get 'types/:id/update_parts' => 'types#update_parts'

  get 'items/update_types', as: 'update_types'
  get 'items/update_parts' => 'types#update_parts'
  get 'items/:id/update_types' => 'items#update_types'
  get 'items/:id/update_parts' => 'types#update_parts'

  get 'roottypes_order' => 'roottypes#order', as: 'roottypes_order'
  get 'parts_order' => 'parts#order', as: 'parts_order'
  get 'types_order' => 'types#order', as: 'types_order'
  get 'items_order' => 'items#order', as: 'items_order'

  get 'roottypes/:id/up_order' => 'roottypes#up_order', as: 'roottypes_up_order'
  get 'roottypes/:id/down_order' => 'roottypes#down_order', as: 'roottypes_down_order'

  get 'parts/:id/up_order' => 'parts#up_order', as: 'parts_up_order'
  get 'parts/:id/down_order' => 'parts#down_order', as: 'parts_down_order'

  get 'types/:id/up_order' => 'types#up_order', as: 'types_up_order'
  get 'types/:id/down_order' => 'types#down_order', as: 'types_down_order'

  get 'items/:id/up_order' => 'items#up_order', as: 'items_up_order'
  get 'items/:id/down_order' => 'items#down_order', as: 'items_down_order'

  post 'callbacks/fast_callback'
  post 'callbacks/slow_callback'
  patch 'callbacks/slow_callback'
  patch 'callbacks/fast_callback'

  resources :admins
  resources :actions
  resources :tidings
  resources :parts
  resources :types
  resources :items
  resources :comments
  resources :captions
  resources :sliders
  resources :uploads
  resources :abouts, :only => [:index, :edit, :update]
  resources :mains, :only => [:index, :edit, :update]
  resources :contacts, :only => [:index]
  resources :globals
  resources :photogals
  resources :photogal_assets, :only => [:edit, :update]
  resources :roottypes
  root 'static#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/publish_item/:id', to: 'items#publish', as: 'publish_item'
  get '/dublicate/:id', to: 'items#dublicate', as: 'dublicate'

  get '/destroy_item_asset/:item_id/:asset_id', to: 'items#destroy_asset', as: 'destroy_item_asset'
  get '/destroy_photogal_asset/:photogal_id/:asset_id', to: 'photogals#destroy_asset', as: 'destroy_photogal_asset'
end

app/controllers/roottypes_controller.rb
class RoottypesController < ApplicationController

  before_action :logged_in_admin, only: [:index, :edit, :update, :new, :order, :up_order, :down_order]

  def edit
    @roottype = Roottype.find(params[:id])
  end

  def new
    @roottype = Roottype.new
  end

  def create
    @roottype = Roottype.new(roottype_params)
    roottypes = Roottype.all
    last_order = roottypes.empty? ? 1 : roottypes.last.order + 1
    @roottype.order = last_order
    if @roottype.save
      # Handle a successful save.
      flash[:success] = "Категория добавлена"
      redirect_to roottypes_url
    else
      render 'new'
    end
  end

  def destroy
    @roottype = Roottype.find(params[:id])
    @roottype.destroy
    flash[:success] = "Категория удалена"
    redirect_to roottypes_url
  end

  def update
    @roottype = Roottype.find(params[:id])
    if @roottype.update_attributes(roottype_params)
      # Handle a successful update.
      flash[:success] = "Категория обновлена"
      redirect_to roottypes_url
    else
      render 'edit'
    end

  end

  def show
    @roottype = Roottype.find(params[:id])
  end

  def index
    @roottypes = Roottype.all
  end

  def up_order
    roottype = Roottype.find(params[:id])

    upper_roottype = Roottype.where(order: roottype.order-1).first
    upper_roottype.update_attributes(order: upper_roottype.order+1)
    roottype.update_attributes(order: roottype.order-1)

    render 'order'
  end

  def down_order
    roottype = Roottype.find(params[:id])

    downer_roottype = Roottype.where(order: roottype.order+1).first
    downer_roottype.update_attributes(order: downer_roottype.order-1)
    roottype.update_attributes(order: roottype.order+1)

    render 'order'
  end

  def order
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def roottype_params
    params.require(:roottype).permit(:title, :order)
  end

  # Confirms a logged-in user.
  def logged_in_admin
    unless logged_in?
      store_location
      flash[:danger] = "Зайдите как администратор"
      redirect_to login_url
    end
  end

end

app/helpers/roottypes_helper.rb
module RoottypesHelper
end

app/views/roottypes/down_order.js.erb
$('.catalog-list').html("<%= render :partial => 'items_tree_menu.html.erb' %>");

app/views/roottypes/edit.html.erb
<% breadcrumb :edit_roottype %>
<%= render 'shared/roottypes_error_messages' %>
<div class="col-md-4 form-group">
  <%= form_for @roottype do |f| %>
      <%= f.label :title, 'Имя категории' %>
      <%= f.text_field :title, :class => 'form-control' %>
      <%= f.submit "Сохранить", :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/roottypes/new.html.erb
<% breadcrumb :add_roottype %>
<%= render 'shared/roottypes_error_messages' %>
<div class="col-md-4 form-group">
  <%= form_for @roottype do |f| %>
      <%= f.label :title, 'Имя категории' %>
      <%= f.text_field :title, :class => 'form-control' %>
      <%= f.submit "Добавить", :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/roottypes/order.html.erb
<% breadcrumb :roottypes_order %>
<% roottypes = Roottype.all %>
<% roottypes.each_with_index do |roottype, index| %>
    <p>
      <% if index != 0 %>
          <%= link_to '', roottypes_up_order_path(roottype.id), :class => "btn-up" %>
      <% end %>
      <% if index != roottypes.count-1 %>
          <%= link_to '', roottypes_down_order_path(roottype.id), :class => "btn-down" %>
      <% end %>
      <% if roottype.parts.count > 0 %>
          <b><%= link_to roottype.title, parts_order_path(roottype_id: roottype.id) %></b>
      <% else %>
          <b><%= roottype.title %></b>
      <% end %>
    </p>
<% end %>

app/views/roottypes/show.html.erb
<% breadcrumb :roottype, @roottype %>

<% if logged_in? %>
    <%= render 'admins/toolbar' %>
<% end %>

<div class="row">
  <%= render 'parts/items_tree_menu' %>
  <div class="col-md-9 catalog">
    <% parts = @roottype.parts %>
    <h2 class="on-main"><%= @roottype.title %></h2>
    <ul>
      <% parts.each do |part| %>
          <% counter = 0 %>
          <% part.types.each do |type| %>
              <% counter += type.items.where("public = ?", true).count %>
          <% end %>
          <% if !logged_in? && counter > 0 %>
              <li><h3><%= link_to "#{part.title}", part_path(part.id) %></h3></li>
          <% elsif logged_in? %>
              <li><h3><%= link_to "#{part.title}", part_path(part.id) %></h3></li>
          <% end %>

          <% types = Type.where(part_id: part.id) %>
          <div class="row row-centered">
            <div class="masonry">
              <% if types.first %>
                  <% types.each do |type| %>
                      <%= render partial: "types/card", :locals => {:type => type} %>
                  <% end %>
              <% end %>
            </div>
          </div>
      <% end %>
    </ul>
    <br>
  </div>
</div>

app/views/roottypes/up_order.js.erb
$('.catalog-list').html("<%= render :partial => 'items_tree_menu.html.erb' %>");